# This workflow aims to release a new version of the project when a commit is pushed to the main branch.

name: Release and publish

on:
  push:
    branches: [main]

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Release a new version
        id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: norelease
          tag_prefix: v
          release_name: <RELEASE_TAG>
          max_commits: 25

      - name: Check output parameters
        run: echo -e "Tag name ${{ steps.release.outputs.tag_name }}\nRelease version ${{ steps.release.outputs.version }}"
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}

  publish-on-release:
    needs: release-on-push
    if: needs.release-on-push.outputs.version != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.17
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          ignore_dev_requirements: "yes"
